"""Add profile fields to User model

Revision ID: 77bed25564bf
Revises: 
Create Date: 2025-05-16 13:56:13.240664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bed25564bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('users', 'auth_provider',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'local'::text"))
    op.drop_index('idx_users_auth_provider', table_name='users')
    op.drop_index('idx_users_provider_user_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_provider_user_id', 'users', ['provider_user_id'], unique=False)
    op.create_index('idx_users_auth_provider', 'users', ['auth_provider'], unique=False)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'local'::text"))
    op.drop_column('users', 'location')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'company')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
